# Generated by Django 2.0.13 on 2019-04-17 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0083_auto_20190417_0830'),
        ('analytics_module', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BeatDemoDownload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('beat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.Beat')),
            ],
        ),
        migrations.CreateModel(
            name='BeatLike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('beat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.Beat')),
            ],
        ),
        migrations.CreateModel(
            name='BeatShare',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('beat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.Beat')),
            ],
        ),
        migrations.AlterField(
            model_name='beatplay',
            name='beat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.Beat'),
        ),
    ]
