# Generated by Django 2.0.13 on 2019-04-17 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0083_auto_20190417_0830'),
        ('analytics_module', '0002_auto_20190417_0830'),
    ]

    operations = [
        migrations.CreateModel(
            name='BeatSold',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('beat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.Beat')),
            ],
        ),
    ]
