# Generated by Django 2.0.13 on 2019-04-17 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics_module', '0003_beatsold'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beatsold',
            name='beat',
        ),
        migrations.DeleteModel(
            name='BeatSold',
        ),
    ]
