# Generated by Django 2.0.13 on 2019-04-17 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics_module', '0005_beatpopularityincrease'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beatlike',
            name='beat',
        ),
        migrations.DeleteModel(
            name='BeatLike',
        ),
    ]
