AWS_BUCKET = 'beatpulse'
AWS_BUCKET_PRIVATE = 'beatpulse-private'
AWS_UPLOAD_REGION = 'eu-central-1'
# beatpulse_s3_uploader
AWS_UPLOAD_ACCESS_KEY_ID = 'AKIAU3PL7636MECP7CE3'
AWS_UPLOAD_SECRET_KEY = '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'
