# Generated by Django 2.1 on 2018-08-23 14:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ArtistType',
        ),
        migrations.AddField(
            model_name='genre',
            name='last_updated',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='this dates is updated when a new beat is added'),
        ),
        migrations.AddField(
            model_name='mood',
            name='last_updated',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='this dates is updated when a new beat is added'),
        ),
        migrations.AddField(
            model_name='playlist',
            name='last_updated',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='this dates is updated when a new beat is added'),
        ),
    ]
