# Generated by Django 2.1 on 2018-08-23 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0002_auto_20180823_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='beats',
            field=models.ManyToManyField(to='models.Beat'),
        ),
    ]
