# Generated by Django 2.1 on 2018-08-24 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0003_playlist_beats'),
    ]

    operations = [
        migrations.CreateModel(
            name='LicenseOptionDescriptionField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=50)),
                ('is_included', models.BooleanField()),
            ],
        ),
        migrations.AddField(
            model_name='producer',
            name='bio',
            field=models.TextField(default='', max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='beat',
            name='key',
            field=models.CharField(blank=True, help_text='For example F#, Cmin', max_length=5),
        ),
        migrations.AlterField(
            model_name='licenseoption',
            name='contract_html',
            field=models.TextField(blank=True, max_length=2000),
        ),
        migrations.AddField(
            model_name='licenseoptiondescriptionfield',
            name='license_option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.LicenseOption'),
        ),
    ]
