# Generated by Django 2.1 on 2018-08-25 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0005_auto_20180824_1012'),
    ]

    operations = [
        migrations.AddField(
            model_name='mood',
            name='beats',
            field=models.ManyToManyField(to='models.Beat'),
        ),
        migrations.AlterField(
            model_name='beat',
            name='genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='genre_beats', to='models.Genre'),
        ),
        migrations.AlterField(
            model_name='beat',
            name='key',
            field=models.CharField(help_text='For example F#, Cmin', max_length=5),
        ),
        migrations.AlterField(
            model_name='beat',
            name='sub_genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sub_genre_beats', to='models.Genre'),
        ),
    ]
