# Generated by Django 2.1 on 2018-08-30 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0007_licenseoption_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='beat',
            old_name='featured',
            new_name='is_featured',
        ),
    ]
