# Generated by Django 2.1.1 on 2018-09-14 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0012_auto_20180910_1631'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mood',
            name='beats',
        ),
        migrations.AddField(
            model_name='beat',
            name='mood',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='mood_beats', to='models.Mood'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='trendingbeat',
            name='period',
            field=models.CharField(choices=[('Today', 'Today'), ('Week', 'This week'), ('Month', 'This month'), ('Year', 'This year'), ('AllTime', 'All time')], help_text='The period', max_length=10),
        ),
    ]
