# Generated by Django 2.1.1 on 2018-09-15 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0013_auto_20180914_1726'),
    ]

    operations = [
        migrations.AddField(
            model_name='producer',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
