# Generated by Django 2.1.1 on 2018-09-25 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0016_playlist_is_popular'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bundledeal',
            name='licenses',
        ),
        migrations.AlterField(
            model_name='coupon',
            name='token',
            field=models.CharField(help_text='The actual code of the coupon', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='beats',
            field=models.ManyToManyField(related_name='playlists', to='models.Beat'),
        ),
        migrations.AlterUniqueTogether(
            name='lyric',
            unique_together={('profile', 'beat')},
        ),
        migrations.DeleteModel(
            name='BundleDeal',
        ),
    ]
