# Generated by Django 2.1.1 on 2018-09-25 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0017_auto_20180925_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='expiration_date',
            field=models.DateField(blank=True, help_text='The expiration date of the coupon', null=True),
        ),
        migrations.AlterField(
            model_name='genre',
            name='order_position',
            field=models.FloatField(blank=True, db_index=True, help_text='The order in the list', null=True),
        ),
        migrations.AlterField(
            model_name='licenseoption',
            name='price',
            field=models.FloatField(default=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mood',
            name='order_position',
            field=models.FloatField(blank=True, db_index=True, help_text='The order in the list', null=True),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='order_position',
            field=models.FloatField(blank=True, db_index=True, help_text='The order in the list', null=True),
        ),
        migrations.AlterField(
            model_name='producer',
            name='image_logo_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
