# Generated by Django 2.1.1 on 2018-09-25 16:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0018_auto_20180925_1343'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producerpayout',
            old_name='payed_on_date',
            new_name='date',
        ),
        migrations.AddField(
            model_name='playlist',
            name='date_of_creation',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='producer',
            name='date_of_creation',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
