# Generated by Django 2.1.1 on 2018-09-25 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0020_auto_20180925_1702'),
    ]

    operations = [
        migrations.RenameField(
            model_name='beat',
            old_name='date_of_publishing',
            new_name='date_of_release',
        ),
    ]
