# Generated by Django 2.1.1 on 2018-09-25 17:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0022_auto_20180925_1710'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genre',
            name='date_of_creation',
        ),
        migrations.RemoveField(
            model_name='mood',
            name='date_of_creation',
        ),
        migrations.AddField(
            model_name='playlist',
            name='date_of_update',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='When its information or beats has changed'),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='date_of_creation',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='when it was first created'),
        ),
    ]
