# Generated by Django 2.0.9 on 2018-10-05 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0024_auto_20181002_0637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beat',
            name='image_url',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='genre',
            name='image_background_url',
            field=models.URLField(default='https://firebasestorage.googleapis.com/v0/b/beatpulse-39fd3.appspot.com/o/beat%20images%2F1-min.jpg?alt=media&token=cfa6bf39-b213-49ea-b5e4-4d7fa93c8b7c', max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='genre',
            name='image_thumbnail_url',
            field=models.URLField(default='https://firebasestorage.googleapis.com/v0/b/beatpulse-39fd3.appspot.com/o/beat%20images%2F1-min.jpg?alt=media&token=cfa6bf39-b213-49ea-b5e4-4d7fa93c8b7c', max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mood',
            name='image_background_url',
            field=models.URLField(default='https://firebasestorage.googleapis.com/v0/b/beatpulse-39fd3.appspot.com/o/beat%20images%2F1-min.jpg?alt=media&token=cfa6bf39-b213-49ea-b5e4-4d7fa93c8b7c', max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mood',
            name='image_thumbnail_url',
            field=models.URLField(default='https://firebasestorage.googleapis.com/v0/b/beatpulse-39fd3.appspot.com/o/beat%20images%2F1-min.jpg?alt=media&token=cfa6bf39-b213-49ea-b5e4-4d7fa93c8b7c', max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='playlist',
            name='image_background_url',
            field=models.URLField(default='https://firebasestorage.googleapis.com/v0/b/beatpulse-39fd3.appspot.com/o/beat%20images%2F1-min.jpg?alt=media&token=cfa6bf39-b213-49ea-b5e4-4d7fa93c8b7c', max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='playlist',
            name='image_thumbnail_url',
            field=models.URLField(default='https://firebasestorage.googleapis.com/v0/b/beatpulse-39fd3.appspot.com/o/beat%20images%2F1-min.jpg?alt=media&token=cfa6bf39-b213-49ea-b5e4-4d7fa93c8b7c', max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='producer',
            name='image_background_url',
            field=models.CharField(default='https://firebasestorage.googleapis.com/v0/b/beatpulse-39fd3.appspot.com/o/beat%20images%2F1-min.jpg?alt=media&token=cfa6bf39-b213-49ea-b5e4-4d7fa93c8b7c', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='producer',
            name='image_logo_url',
            field=models.CharField(default='https://firebasestorage.googleapis.com/v0/b/beatpulse-39fd3.appspot.com/o/beat%20images%2F1-min.jpg?alt=media&token=cfa6bf39-b213-49ea-b5e4-4d7fa93c8b7c', max_length=255),
            preserve_default=False,
        ),
    ]
