# Generated by Django 2.0.9 on 2018-11-01 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0026_lyric_lyric'),
    ]

    operations = [
        migrations.AddField(
            model_name='beat',
            name='exclusive_price',
            field=models.FloatField(blank=True, help_text='The price to buy this beat with exclusivity', null=True),
        ),
    ]
