# Generated by Django 2.1.3 on 2018-11-06 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0029_auto_20181106_1323'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image_avatar_url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
