# Generated by Django 2.1.3 on 2018-11-09 17:00

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0030_profile_image_avatar_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='beat',
            name='color',
            field=colorfield.fields.ColorField(default='#00000000', help_text='the color represeting the beat. it is used as a shadow light in the app', max_length=18),
            preserve_default=False,
        ),
    ]
