# Generated by Django 2.1.3 on 2018-11-09 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0031_beat_color'),
    ]

    operations = [
        migrations.RenameField(
            model_name='beat',
            old_name='color',
            new_name='color_hex',
        ),
    ]
