# Generated by Django 2.1.3 on 2018-11-19 18:51

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0033_auto_20181110_1600'),
    ]

    operations = [
        migrations.AddField(
            model_name='beat',
            name='tags',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=list, help_text='tags to help with beat search'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='beat',
            name='waveform_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=list, help_text='the data points needed to create the audio wave form'),
            preserve_default=False,
        ),
    ]
