# Generated by Django 2.1.3 on 2018-11-24 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0034_auto_20181119_1851'),
    ]

    operations = [
        migrations.CreateModel(
            name='BeatProducerRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commission', models.FloatField()),
            ],
        ),
        migrations.RemoveField(
            model_name='beat',
            name='producers',
        ),
        migrations.AddField(
            model_name='beatproducerrelation',
            name='beat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.Beat'),
        ),
        migrations.AddField(
            model_name='beatproducerrelation',
            name='producer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.Producer'),
        ),
        migrations.AddField(
            model_name='beat',
            name='producers_new',
            field=models.ManyToManyField(through='models.BeatProducerRelation', to='models.Producer'),
        ),
    ]
