# Generated by Django 2.1.3 on 2018-11-30 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0036_auto_20181124_0804'),
    ]

    operations = [
        migrations.CreateModel(
            name='BeatKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=25)),
            ],
        ),
        migrations.AlterField(
            model_name='beat',
            name='demo_download_allowed',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='beat',
            name='is_featured',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='is_never_expiring',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='genre',
            name='is_featured_on_browse',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='licenseoption',
            name='has_mp3',
            field=models.BooleanField(help_text='True if the user will be able to get mp3'),
        ),
        migrations.AlterField(
            model_name='licenseoption',
            name='is_featured',
            field=models.BooleanField(help_text='True if this licence will stand out'),
        ),
        migrations.AlterField(
            model_name='mood',
            name='is_featured_on_browse',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='is_featured_on_browse',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='is_featured_on_playlists',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='is_popular',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='producer',
            name='is_featured',
            field=models.BooleanField(),
        ),
    ]
