# Generated by Django 2.1.3 on 2018-12-20 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0039_auto_20181130_1008'),
    ]

    operations = [
        migrations.RenameField(
            model_name='genre',
            old_name='is_featured_on_browse',
            new_name='is_popular',
        ),
        migrations.RenameField(
            model_name='mood',
            old_name='is_featured_on_browse',
            new_name='is_popular',
        ),
    ]
