# Generated by Django 2.0.9 on 2019-01-07 11:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0040_auto_20181220_1628'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PartialOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='genre',
            name='last_updated',
        ),
        migrations.RemoveField(
            model_name='mood',
            name='last_updated',
        ),
        migrations.RemoveField(
            model_name='playlist',
            name='last_updated',
        ),
        migrations.AddField(
            model_name='beat',
            name='image_thumbnail_url',
            field=models.CharField(default='', help_text='A scalded version of the image. It should be 100x100', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='genre',
            name='date_of_update',
            field=models.DateTimeField(auto_now=True, help_text='this dates is updated when a new beat is added'),
        ),
        migrations.AddField(
            model_name='mood',
            name='date_of_update',
            field=models.DateTimeField(auto_now=True, help_text='this dates is updated when a new beat is added'),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='date_of_creation',
            field=models.DateTimeField(auto_now_add=True, help_text='when it was first created'),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='date_of_update',
            field=models.DateTimeField(auto_now=True, help_text='this dates is updated when a new beat is added'),
        ),
        migrations.AlterField(
            model_name='producer',
            name='date_of_creation',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='producerpayout',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='date_of_creation',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AddField(
            model_name='partialorder',
            name='beat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='models.Beat'),
        ),
        migrations.AddField(
            model_name='partialorder',
            name='license',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='models.LicenseOption'),
        ),
        migrations.AddField(
            model_name='partialorder',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='models.Order'),
        ),
        migrations.AddField(
            model_name='order',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
