# Generated by Django 2.0.9 on 2019-01-09 11:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0041_auto_20190107_1114'),
    ]

    operations = [
        migrations.CreateModel(
            name='LicenseBought',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=150)),
                ('price', models.FloatField()),
                ('color_hex', models.CharField(max_length=10)),
                ('is_featured', models.BooleanField(help_text='True if this licence will stand out')),
                ('has_mp3', models.BooleanField(help_text='True if the user will be able to get mp3')),
                ('has_wav', models.BooleanField()),
                ('has_trackout', models.BooleanField()),
                ('contract_html', models.TextField(blank=True, max_length=2000)),
                ('price_discounted', models.FloatField(help_text='The price paid for the license after deals and coupons')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItemDownload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('profile_ip', models.CharField(help_text='The IP of the customer when he made the download', max_length=15)),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.OrderItem')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItemIncome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('income', models.FloatField()),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='models.OrderItem')),
                ('producer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='models.Producer')),
            ],
        ),
        migrations.CreateModel(
            name='ProducerPayoutDescriptionField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('amount', models.FloatField()),
            ],
        ),
        migrations.RemoveField(
            model_name='partialorder',
            name='beat',
        ),
        migrations.RemoveField(
            model_name='partialorder',
            name='license',
        ),
        migrations.RemoveField(
            model_name='partialorder',
            name='order',
        ),
        migrations.AddField(
            model_name='beat',
            name='trackout_external_url',
            field=models.URLField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_platform',
            field=models.CharField(choices=[('Stripe', 'Stripe'), ('Paypal', 'Paypal')], default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='profile_address',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='profile_ip',
            field=models.CharField(default='', help_text='The IP of the customer when he made the payment', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='profile_platform',
            field=models.CharField(choices=[('Web', 'Web'), ('Android', 'Android'), ('iOS', 'iOS')], default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Complete', 'Complete'), ('Reverse', 'Reverse'), ('Refunded', 'Refunded')], default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='producerpayout',
            name='producer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='models.Producer'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='platform',
            field=models.CharField(choices=[('Web', 'Web'), ('Android', 'Android'), ('iOS', 'iOS')], default='', max_length=10),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='PartialOrder',
        ),
        migrations.AddField(
            model_name='producerpayoutdescriptionfield',
            name='producer_payout',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='description_fields', to='models.ProducerPayout'),
        ),
        migrations.AddField(
            model_name='orderitemdownload',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='beat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='models.Beat'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='license',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.LicenseBought'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='models.Order'),
        ),
    ]
