# Generated by Django 2.1.4 on 2019-01-13 11:35

import colorfield.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0042_auto_20190109_1113'),
    ]

    operations = [
        migrations.RenameField(
            model_name='beat',
            old_name='deleted',
            new_name='is_deleted',
        ),
        migrations.RenameField(
            model_name='beat',
            old_name='published',
            new_name='is_published',
        ),
        migrations.AlterField(
            model_name='beat',
            name='bpm',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='beat',
            name='color_hex',
            field=colorfield.fields.ColorField(help_text='the color represeting the beat. it is used as a shadow light in the app', max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='beat',
            name='genre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='beats', to='models.Genre'),
        ),
        migrations.AlterField(
            model_name='beat',
            name='image_thumbnail_url',
            field=models.CharField(help_text='A scalded version of the image. It should be 100x100', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='beat',
            name='image_url',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='beat',
            name='key',
            field=models.ForeignKey(help_text='For example F#, Cmin', null=True, on_delete=django.db.models.deletion.PROTECT, to='models.BeatKey'),
        ),
        migrations.AlterField(
            model_name='beat',
            name='length',
            field=models.PositiveSmallIntegerField(help_text='Length in seconds of the track', null=True),
        ),
        migrations.AlterField(
            model_name='beat',
            name='mood',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='beats', to='models.Mood'),
        ),
        migrations.AlterField(
            model_name='beat',
            name='sub_genre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subgenre_beats', to='models.Genre'),
        ),
    ]
