# Generated by Django 2.1.4 on 2019-01-13 12:05

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0043_auto_20190113_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beat',
            name='waveform_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(help_text='the data points needed to create the audio wave form', null=True),
        ),
    ]
