# Generated by Django 2.0.10 on 2019-01-17 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0044_auto_20190113_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='license',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='models.LicenseBought'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='models.Order'),
        ),
        migrations.AlterField(
            model_name='orderitemincome',
            name='order_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incomes', to='models.OrderItem'),
        ),
    ]
