# Generated by Django 2.0.10 on 2019-01-29 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0047_auto_20190118_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='fake_followers',
            field=models.IntegerField(default=531),
        ),
        migrations.AddField(
            model_name='producer',
            name='fake_followers',
            field=models.IntegerField(default=531),
        ),
    ]
