# Generated by Django 2.0.10 on 2019-01-29 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0048_auto_20190129_1347'),
    ]

    operations = [
        migrations.AddField(
            model_name='producer',
            name='is_popular',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
