# Generated by Django 2.0.10 on 2019-02-07 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0049_producer_is_popular'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Complete', 'Complete'), ('Complete', 'Complete'), ('Reverse', 'Reverse'), ('Refunded', 'Refunded')], default='Pending', max_length=10),
        ),
    ]
