# Generated by Django 2.0.10 on 2019-02-19 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0051_order_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_platform',
            field=models.CharField(choices=[('Credit Card', 'Credit Card'), ('Paypal', 'Paypal'), ('Alipay', 'Alipay')], max_length=25),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Complete', 'Complete'), ('Reverse', 'Reverse'), ('Refunded', 'Refunded')], default='Pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='total',
            field=models.FloatField(help_text='The total price the client paid after coupons and deals'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='models.Order'),
        ),
        migrations.AlterField(
            model_name='orderitemincome',
            name='order_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incomes', to='models.OrderItem'),
        ),
        migrations.AlterField(
            model_name='orderitemincome',
            name='producer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.Producer'),
        ),
    ]
