# Generated by Django 2.0.10 on 2019-02-21 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0053_auto_20190221_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitemdownload',
            name='profile_ip',
            field=models.CharField(help_text='The IP of the customer when he made the download', max_length=45),
        ),
    ]
