# Generated by Django 2.0.10 on 2019-02-22 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0054_auto_20190221_1510'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountInvitation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=50, unique=True)),
                ('role', models.CharField(choices=[('Admin', 'Admin'), ('Editor', 'Editor'), ('Producer', 'Producer')], max_length=10)),
                ('email_sent_to', models.EmailField(blank=True, max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_platform',
            field=models.CharField(choices=[('Credit Card', 'Credit Card'), ('PayPal', 'PayPal'), ('Alipay', 'Alipay')], max_length=25),
        ),
    ]
