# Generated by Django 2.0.10 on 2019-02-22 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0055_auto_20190222_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountinvitation',
            name='full_name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
