# Generated by Django 2.0.10 on 2019-02-22 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0057_auto_20190222_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountinvitation',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Uploader', 'Uploader'), ('Producer', 'Producer')], max_length=10),
        ),
    ]
