# Generated by Django 2.0.10 on 2019-02-26 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0059_auto_20190222_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='beat',
            name='shareble_link',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='genre',
            name='shareble_link',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='mood',
            name='shareble_link',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='playlist',
            name='shareble_link',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='producer',
            name='shareble_link',
            field=models.URLField(null=True),
        ),
    ]
