# Generated by Django 2.0.10 on 2019-03-05 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0060_auto_20190226_1413'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='slug',
            field=models.SlugField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mood',
            name='slug',
            field=models.SlugField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='playlist',
            name='slug',
            field=models.SlugField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producer',
            name='slug',
            field=models.SlugField(default='', max_length=40),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='producer',
            name='display_name',
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
