# Generated by Django 2.0.10 on 2019-03-12 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0062_auto_20190305_1634'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producer',
            old_name='image_background_url',
            new_name='image_background_file_path',
        ),
        migrations.RenameField(
            model_name='producer',
            old_name='image_logo_url',
            new_name='image_logo_file_path',
        ),
    ]
