# Generated by Django 2.0.10 on 2019-03-12 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0064_auto_20190312_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='image_background_file_path',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='genre',
            name='image_thumbnail_file_path',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='mood',
            name='image_background_file_path',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='mood',
            name='image_thumbnail_file_path',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='image_background_file_path',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='image_thumbnail_file_path',
            field=models.CharField(max_length=500),
        ),
    ]
