# Generated by Django 2.0.10 on 2019-03-12 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0065_auto_20190312_1138'),
    ]

    operations = [
        migrations.RenameField(
            model_name='beat',
            old_name='image_url',
            new_name='image_file_path',
        ),
        migrations.RenameField(
            model_name='beat',
            old_name='image_thumbnail_url',
            new_name='image_thumbnail_file_path',
        ),
    ]
