# Generated by Django 2.0.13 on 2019-03-15 15:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0066_auto_20190312_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producer',
            name='commission',
            field=models.PositiveSmallIntegerField(default=50, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
