# Generated by Django 2.0.13 on 2019-03-15 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0067_auto_20190315_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producer',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='producer',
            name='is_popular',
            field=models.BooleanField(default=False),
        ),
    ]
