# Generated by Django 2.0.13 on 2019-03-22 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0069_auto_20190319_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountinvitation',
            name='email_sent_to',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='accountinvitation',
            name='token',
            field=models.UUIDField(unique=True),
        ),
    ]
