# Generated by Django 2.1.7 on 2019-04-06 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0072_auto_20190322_1001'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='country',
            field=models.CharField(blank=True, max_length=55),
        ),
    ]
