# Generated by Django 2.0.13 on 2019-04-09 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0075_auto_20190408_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='profile_email',
            field=models.EmailField(default='', max_length=254),
            preserve_default=False,
        ),
    ]
