# Generated by Django 2.0.13 on 2019-04-09 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0076_order_profile_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='date_of_creation',
            field=models.DateField(auto_now_add=True),
        ),
    ]
