# Generated by Django 2.0.13 on 2019-04-12 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0077_auto_20190409_0946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image_avatar_file_path',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
