# Generated by Django 2.0.13 on 2019-04-17 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0080_auto_20190412_1443'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beat',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='beat',
            name='waveform_data',
        ),
    ]
