# Generated by Django 2.0.13 on 2019-04-17 07:18

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0081_auto_20190417_0715'),
    ]

    operations = [
        migrations.AddField(
            model_name='beat',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=25), blank=True, help_text='tags to help with beat search', null=True, size=10),
        ),
        migrations.AddField(
            model_name='beat',
            name='waveform_data',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, help_text='the data points needed to create the audio wave form', null=True, size=150),
        ),
    ]
