# Generated by Django 2.0.13 on 2019-04-17 08:30

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0082_auto_20190417_0718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beat',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=25), blank=True, help_text='tags to help with beat search', null=True, size=5),
        ),
    ]
