# Generated by Django 2.0.13 on 2019-04-17 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0084_auto_20190417_0850'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlist',
            name='fake_followers',
        ),
        migrations.RemoveField(
            model_name='producer',
            name='fake_followers',
        ),
    ]
