# Generated by Django 2.2 on 2019-04-20 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0085_auto_20190417_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitemincome',
            name='order_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='producer_incomes', to='models.OrderItem'),
        ),
    ]
