# Generated by Django 2.2 on 2019-04-23 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0086_auto_20190420_1008'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderStripe',
            fields=[
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='models.Order')),
                ('stripe_id', models.CharField(max_length=100)),
            ],
        ),
    ]
