# Generated by Django 2.2 on 2019-04-23 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0087_orderstripe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderstripe',
            name='stripe_id',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
