# Generated by Django 2.2 on 2019-04-23 13:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0088_auto_20190423_1242'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileStripe',
            fields=[
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('customer_id', models.CharField(max_length=100, unique=True)),
            ],
        ),
    ]
