# Generated by Django 2.2 on 2019-04-23 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0089_profilestripe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billinginfo',
            name='stripe_id',
        ),
    ]
