# Generated by Django 2.2 on 2019-04-29 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0091_auto_20190429_0701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beat',
            name='mp3_file_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='beat',
            name='trackout_external_url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='beat',
            name='trackout_file_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='beat',
            name='wav_file_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
