# Generated by Django 2.2 on 2019-04-29 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0092_auto_20190429_0909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beat',
            name='tagged_file_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
