# Generated by Django 2.2 on 2019-04-29 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0093_auto_20190429_0912'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderstripe',
            name='stripe_id',
        ),
        migrations.AddField(
            model_name='orderstripe',
            name='stripe_charge_id',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='orderstripe',
            name='stripe_session_id',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
