# Generated by Django 2.2 on 2019-04-30 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0094_auto_20190429_1656'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beat',
            name='demo_download_allowed',
        ),
    ]
