# Generated by Django 2.2.1 on 2019-05-08 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0095_remove_beat_demo_download_allowed'),
    ]

    operations = [
        migrations.AddField(
            model_name='billinginfo',
            name='stripe_customer_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.DeleteModel(
            name='ProfileStripe',
        ),
    ]
