# Generated by Django 2.2.1 on 2019-05-09 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0096_auto_20190508_1345'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderstripe',
            name='stripe_source_id',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
