# Generated by Django 2.2.1 on 2019-05-09 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0097_orderstripe_stripe_source_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='total_spent',
        ),
    ]
