# Generated by Django 2.2.1 on 2019-05-26 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0098_remove_profile_total_spent'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderPaypal',
            fields=[
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='models.Order')),
                ('charge_id', models.CharField(max_length=100, null=True, unique=True)),
            ],
        ),
        migrations.RenameField(
            model_name='orderstripe',
            old_name='stripe_charge_id',
            new_name='charge_id',
        ),
        migrations.RenameField(
            model_name='orderstripe',
            old_name='stripe_session_id',
            new_name='session_id',
        ),
        migrations.RenameField(
            model_name='orderstripe',
            old_name='stripe_source_id',
            new_name='source_id',
        ),
    ]
