# Generated by Django 2.2.1 on 2019-05-27 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0099_auto_20190526_0953'),
    ]

    operations = [
        migrations.AddField(
            model_name='licensebought',
            name='detailed_license_url',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='licenseoption',
            name='detailed_license_url',
            field=models.URLField(null=True),
        ),
    ]
