# Generated by Django 2.2.1 on 2019-05-28 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0100_auto_20190527_0825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licensebought',
            name='contract_html',
            field=models.TextField(blank=True, max_length=10000),
        ),
        migrations.AlterField(
            model_name='licenseoption',
            name='contract_html',
            field=models.TextField(blank=True, max_length=10000),
        ),
    ]
