# Generated by Django 2.2.1 on 2019-05-28 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0101_auto_20190528_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licensebought',
            name='contract_html',
            field=models.TextField(blank=True, max_length=15000),
        ),
        migrations.AlterField(
            model_name='licenseoption',
            name='contract_html',
            field=models.TextField(blank=True, max_length=15000),
        ),
    ]
