# Generated by Django 2.2.2 on 2019-06-07 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0102_auto_20190528_1104'),
    ]

    operations = [
        migrations.AddField(
            model_name='beat',
            name='energy',
            field=models.PositiveSmallIntegerField(default=1, help_text='A number between 1 and 10'),
        ),
        migrations.AddField(
            model_name='beat',
            name='stream_file_path',
            field=models.CharField(blank=True, help_text='The ogg file used to stream the beat', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='beat',
            name='shareble_link',
            field=models.URLField(help_text='link that is shared between devices and that will open the app directly', null=True),
        ),
    ]
