# Generated by Django 2.2.2 on 2019-06-07 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0103_auto_20190607_0641'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beat',
            name='bought_exlusive_license',
        ),
    ]
