# Generated by Django 2.2.2 on 2019-06-07 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0104_remove_beat_bought_exlusive_license'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beat',
            name='exclusive_price',
        ),
    ]
