# Generated by Django 2.2.2 on 2019-06-25 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0105_remove_beat_exclusive_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='producer',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
