# Generated by Django 2.2.3 on 2019-08-20 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0108_orderpaypal_json_result'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderpaypal',
            old_name='charge_id',
            new_name='paypal_order_id',
        ),
    ]
