# Generated by Django 2.2.3 on 2019-08-20 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0110_auto_20190820_1015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderpaypal',
            name='paypal_payment_capture_id',
        ),
        migrations.AddField(
            model_name='orderpaypal',
            name='payment_capture_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
