# Generated by Django 2.2.3 on 2019-08-20 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0112_auto_20190820_1021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderpaypal',
            name='approved_order_id',
        ),
    ]
