# Generated by Django 2.2.3 on 2020-04-28 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0113_remove_orderpaypal_approved_order_id'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='followedplaylist',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='followedproducer',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='likedbeat',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='lyric',
            unique_together=set(),
        ),
    ]
